### ISSUE TITLE
Find a way to expose to plugins which plugins are loaded

### ISSUE THREAD

**Issue by Corpelijn** [Agadar/DankTimesBot#129] opened 2022-03-03 09:34 UTC
For the next update of the HorseRaces plugin, the Items plugin is required as dependency. How can we make the HorseRaces plugin use the Items plugin, without the plugin crashing if the Items plugin is not loaded.

**Comment by Agadar** [comment] 2022-03-05 17:00
Title and description seem to be two separate issues.

For the HorseRaces items issue in the description, seems to be a duplicate of https://github.com/Agadar/DankTimesBot-Plugin-Items/issues/18.

Plan for core bot is to expose a function in abstract plugin to allow getting a list of loaded plugins.

**Comment by Agadar** [comment] 2022-06-05 17:12
Implemented in 43a578bb192380b26ea1662d9615f1261624ceb2.

**Closed by Agadar** 2022-06-05 17:12 UTC
Labels: enhancement
